"""change recipe_id to uuid

Revision ID: 6bd169781446
Revises: dfd3983ff605
Create Date: 2020-11-11 14:30:38.980601

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6bd169781446'
down_revision = 'dfd3983ff605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rating')
    # op.drop_table('recipe_cart')
    # op.drop_table('recipe_ingredient')
    op.drop_table('recipe')
    # op.create_foreign_key(None, 'user_favourites', 'recipe', ['recipe_id'], ['recipe_id'])
    # op.create_foreign_key(None, 'user_rating', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rating', type_='foreignkey')
    op.drop_constraint(None, 'user_favourites', type_='foreignkey')
    # ### end Alembic commands ###
