"""add uuid

Revision ID: dfed6d5ebd5b
Revises: 65f60321db69
Create Date: 2020-11-11 15:00:12.127524

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'dfed6d5ebd5b'
down_revision = '65f60321db69'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_notes')
    # op.drop_table('user_rating')
    # op.drop_table('pantry_list')
    # op.drop_table('recipe_cart')
    # op.drop_table('recipe_ingredient')
    # op.drop_table('shopping_list')
    # op.drop_table('user_favourites')
    op.drop_table('user')
    op.drop_table('recipe')
    # op.create_table('user_favourites',
    # sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    # sa.Column('recipe_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    # sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    # sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    # )
    # op.drop_index('user_rating_ibfk_1', table_name='user_rating')
    # op.create_foreign_key(None, 'user_rating', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rating', type_='foreignkey')
    op.create_index('user_rating_ibfk_1', 'user_rating', ['recipe_id'], unique=False)
    op.drop_table('user_favourites')
    # ### end Alembic commands ###
