"""Created consumed recipes table

Revision ID: f515c49006fd
Revises: 9ed74c71d84a
Create Date: 2020-11-11 19:01:31.771294

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f515c49006fd'
down_revision = '9ed74c71d84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumed_recipes',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('recipe_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('consumption_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumed_recipes')
    # ### end Alembic commands ###
