"""update fav list

Revision ID: fc2d1a3487b0
Revises: dcc7a1645fa6
Create Date: 2020-11-10 20:05:21.275641

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc2d1a3487b0'
down_revision = 'dcc7a1645fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites_list', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites_list', sa.Column('id', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
