"""empty message

Revision ID: 0d57cdde0bc8
Revises: 806bba569271
Create Date: 2020-10-23 00:51:53.656538

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0d57cdde0bc8'
down_revision = '806bba569271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('recipe_name', sa.String(length=100), nullable=False),
    sa.Column('cuisine', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.String(length=100), nullable=False),
    sa.Column('time_to_cook_in_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('favourites_list',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites_list')
    op.drop_table('recipe')
    # ### end Alembic commands ###
