"""update fav list

Revision ID: 33d490ad9a9a
Revises: 5d9adc826605
Create Date: 2020-11-10 23:58:16.545883

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '33d490ad9a9a'
down_revision = '5d9adc826605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_cart_ibfk_1', 'recipe_cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('recipe_cart_ibfk_1', 'recipe_cart', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###
