"""update fav list

Revision ID: 3461c9ab2ed8
Revises: e15c9f833955
Create Date: 2020-11-10 19:42:36.068792

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3461c9ab2ed8'
down_revision = 'e15c9f833955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favourites_list', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'favourites_list', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites_list', type_='foreignkey')
    op.drop_constraint(None, 'favourites_list', type_='foreignkey')
    # ### end Alembic commands ###
