"""empty message

Revision ID: 7007faeb2065
Revises: b2726b4264e0
Create Date: 2020-11-09 18:47:29.769836

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7007faeb2065'
down_revision = 'b2726b4264e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'spoonacular_recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('spoonacular_recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
