"""empty message

Revision ID: 9b96686f4d2c
Revises: 05006b3b0796
Create Date: 2020-11-08 23:04:19.950006

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9b96686f4d2c'
down_revision = '05006b3b0796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('spoonacular_recipe_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'spoonacular_recipe_id')
    # ### end Alembic commands ###
