"""empty message

Revision ID: bf45058f71e8
Revises: beb14750038d
Create Date: 2020-10-21 16:17:47.802342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf45058f71e8'
down_revision = 'beb14750038d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('testDB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testDB',
    sa.Column('string_column', mysql.VARCHAR(length=140), nullable=False),
    sa.Column('integer_column', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_column', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('string_column'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
