"""update fav list

Revision ID: dcc7a1645fa6
Revises: 3461c9ab2ed8
Create Date: 2020-11-10 20:01:38.115711

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'dcc7a1645fa6'
down_revision = '3461c9ab2ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites_list', sa.Column('id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites_list', 'id')
    # ### end Alembic commands ###
