"""update fav list

Revision ID: e15c9f833955
Revises: 7007faeb2065
Create Date: 2020-11-10 19:36:23.950857

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e15c9f833955'
down_revision = '7007faeb2065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favourites_list_ibfk_2', 'favourites_list', type_='foreignkey')
    op.drop_constraint('favourites_list_ibfk_1', 'favourites_list', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favourites_list_ibfk_1', 'favourites_list', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('favourites_list_ibfk_2', 'favourites_list', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###
