"""empty message

Revision ID: ec73a35dd4e0
Revises: 9b96686f4d2c
Create Date: 2020-11-09 17:32:32.359545

"""
from alembic import op
import sqlalchemy as sa
import app
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec73a35dd4e0'
down_revision = '9b96686f4d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(length=100), nullable=False))
    op.drop_column('recipe', 'recipe_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_image', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
