const CONSTANTS = {};

CONSTANTS.APP_NAME = 'ChefCoPilot';

// Used for deployment
// CONSTANTS.BACKEND_URL = 'https://chefcopilotbackend.herokuapp.com';

CONSTANTS.LOCAL_HOST_BACKEND_URL = "http://localhost:3001";
CONSTANTS.BACKEND_URL = 'http://localhost:3001'//'https://chefcopilotbackend.herokuapp.com';

CONSTANTS.ERROR_MESSAGE = {};

CONSTANTS.ERROR_MESSAGE.LIST_DELETE = 'Request to delete list item failed:';
CONSTANTS.ERROR_MESSAGE.LIST_ADD = 'Request to add list item failed:';
CONSTANTS.ERROR_MESSAGE.LIST_GET = 'Request to get list items failed:';
CONSTANTS.ERROR_MESSAGE.LIST_EMPTY_MESSAGE = 'Please enter a valid message';

CONSTANTS.ERROR_MESSAGE.MASTERDETAIL_GET =
  'Request to get master detail text failed:';

CONSTANTS.ENDPOINT = {};
CONSTANTS.ENDPOINT.LIST = `${CONSTANTS.BACKEND_URL}/api/list`;
CONSTANTS.ENDPOINT.MASTERDETAIL = `${CONSTANTS.BACKEND_URL}/api/masterdetail`;
CONSTANTS.ENDPOINT.REMOVE_SHOPPING_LIST_ITEM = `${CONSTANTS.BACKEND_URL}/api/remove_item_from_shopping_list`;
CONSTANTS.ENDPOINT.ADD_SHOPPING_LIST_ITEM = `${CONSTANTS.BACKEND_URL}/api/add_item_to_shopping_list`;
CONSTANTS.ENDPOINT.REGISTER = `${CONSTANTS.BACKEND_URL}/api/add_user`;
CONSTANTS.ENDPOINT.LOGIN = `${CONSTANTS.BACKEND_URL}/api/login`;
CONSTANTS.ENDPOINT.GET_USER = `${CONSTANTS.BACKEND_URL}/api/get_user`;
CONSTANTS.ENDPOINT.LOGOUT = `${CONSTANTS.BACKEND_URL}/api/logout`;
CONSTANTS.ENDPOINT.SHOPPING_LIST = `${CONSTANTS.BACKEND_URL}/api/shopping_list`;
CONSTANTS.ENDPOINT.GET_ALL_RECIPES = `${CONSTANTS.BACKEND_URL}/api/recipes`
CONSTANTS.ENDPOINT.GET_ALL_INGREDIENTS_BY_RECIPE_ID = `${CONSTANTS.LOCAL_HOST_BACKEND_URL}/api/ingredients`
CONSTANTS.ENDPOINT.FAVOURITES_LIST = `${CONSTANTS.BACKEND_URL}/api/favourites_list`;
CONSTANTS.ENDPOINT.RECIPE_CART = `${CONSTANTS.BACKEND_URL}/api/recipe_cart`;
CONSTANTS.ENDPOINT.USER_RATING = `${CONSTANTS.BACKEND_URL}/api/user_rating`;
CONSTANTS.ENDPOINT.USER_NOTES = `${CONSTANTS.BACKEND_URL}/api/user_notes`;
CONSTANTS.ENDPOINT.ADD_CONSUMED_RECIPE = `${CONSTANTS.BACKEND_URL}/api/calorie_tracker/add`;
CONSTANTS.ENDPOINT.REMOVE_CONSUMED_RECIPE = `${CONSTANTS.BACKEND_URL}/api/calorie_tracker/delete`;
CONSTANTS.ENDPOINT.GET_CONSUMED_RECIPES = `${CONSTANTS.BACKEND_URL}/api/calorie_tracker`;

export default CONSTANTS;
